
# example config file for UCAgent
# you can copy this file to ~/.ucagent/setting.yaml and modify it as needed

#openai:
#  model_name: "$(OPENAI_MODEL: Qwen/Qwen3-Coder-30B-A3B-Instruct)"
#  openai_api_key: "$(OPENAI_API_KEY: YOUR_API_KEY)"
#  openai_api_base: "$(OPENAI_API_BASE: http://<your_chat_model_url>/v1)"

#embed:
#  model_name: "$(EMBED_MODEL: Qwen/Qwen3-Embedding-0.6B)"
#  openai_api_key: "$(EMBED_OPENAI_API_KEY: YOUR_API_KEY)"
#  openai_api_base: "$(EMBED_OPENAI_API_BASE: http://<your_embedding_model_url>/v1)"
#  dims: 4096

#langfuse:
#  enable: $(ENABLE_LANGFUSE, false)
#  public_key: $(LANGFUSE_PUBLIC_KEY, <YOUR_LANGFUSE_PUBLIC_KEY>)
#  secret_key: $(LANGFUSE_SECRET_KEY, <YOUR_LANGFUSE_SECRET_KEY>)
#  base_url: $(LANGFUSE_URL, http://localhost:3000)
